version: '3'
services:

  ## Router
  mongos01:
    image: mongo:6.0.1
    container_name: mongos01
    command: mongos --port 27017 --configdb rs-configs/configs01:27017,configs02:27017,configs03:27017 --bind_ip_all
    ports:
      - 27117:27017
    restart: always
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_mongos01_db:/data/db
      - mongodb_cluster_mongos01_config:/data/configdb
  mongos02:
    image: mongo:6.0.1
    container_name: mongos02
    command: mongos --port 27017 --configdb rs-configs/configs01:27017,configs02:27017,configs03:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_mongos02_db:/data/db
      - mongodb_cluster_mongos02_config:/data/configdb
    ports:
      - 27118:27017
    restart: always
    links:
      - mongos01

  ## Config Servers
  configs01:
    image: mongo:6.0.1
    container_name: mongo-configs01
    command: mongod --port 27017 --configsvr --replSet rs-configs
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configs01_db:/data/db
      - mongodb_cluster_configs01_config:/data/configdb
    ports:
      - 27119:27017
    restart: always
    links:
      - shard01-a
      - shard02-a
      - shard03-a
  configs02:
    image: mongo:6.0.1
    container_name: mongo-configs02
    command: mongod --port 27017 --configsvr --replSet rs-configs
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configs02_db:/data/db
      - mongodb_cluster_configs02_config:/data/configdb
    ports:
      - 27120:27017
    restart: always
    links:
      - configs01
  configs03:
    image: mongo:6.0.1
    container_name: mongo-configs03
    command: mongod --port 27017 --configsvr --replSet rs-configs
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_configs03_db:/data/db
      - mongodb_cluster_configs03_config:/data/configdb
    ports:
      - 27121:27017
    restart: always
    links:
      - configs02

  ## Shards
  ## Shards 01

  shard01-a:
    image: mongo:6.0.1
    container_name: shard01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard01
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_a_db:/data/db
      - mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27122:27017
    restart: always
    links:
      - shard01-b
      - shard01-c
  shard01-b:
    image: mongo:6.0.1
    container_name: shard01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard01
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_b_db:/data/db
      - mongodb_cluster_shard01_b_config:/data/configdb
    ports:
      - 27123:27017
    restart: always
  shard01-c:
    image: mongo:6.0.1
    container_name: shard01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard01
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard01_c_db:/data/db
      - mongodb_cluster_shard01_c_config:/data/configdb
    ports:
      - 27124:27017
    restart: always

  ## Shards 02
  shard02-a:
    image: mongo:6.0.1
    container_name: shard02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_a_db:/data/db
      - mongodb_cluster_shard02_a_config:/data/configdb
    ports:
      - 27125:27017
    restart: always
    links:
      - shard02-b
      - shard02-c
  shard02-b:
    image: mongo:6.0.1
    container_name: shard02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_b_db:/data/db
      - mongodb_cluster_shard02_b_config:/data/configdb
    ports:
      - 27126:27017
    restart: always
  shard02-c:
    image: mongo:6.0.1
    container_name: shard02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard02
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard02_c_db:/data/db
      - mongodb_cluster_shard02_c_config:/data/configdb
    ports:
      - 27127:27017
    restart: always

  ## Shards 03
  shard03-a:
    image: mongo:6.0.1
    container_name: shard03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard03
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard03_a_db:/data/db
      - mongodb_cluster_shard03_a_config:/data/configdb
    ports:
      - 27128:27017
    restart: always
    links:
      - shard03-b
      - shard03-c
  shard03-b:
    image: mongo:6.0.1
    container_name: shard03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard03
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard03_b_db:/data/db
      - mongodb_cluster_shard03_b_config:/data/configdb
    ports:
      - 27129:27017
    restart: always
  shard03-c:
    image: mongo:6.0.1
    container_name: shard03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard03
    volumes:
      - ./scripts:/scripts
      - mongodb_cluster_shard03_c_db:/data/db
      - mongodb_cluster_shard03_c_config:/data/configdb
    ports:
      - 27130:27017
    restart: always

volumes:
  mongodb_cluster_mongos01_db:
  mongodb_cluster_mongos01_config:

  mongodb_cluster_mongos02_db:
  mongodb_cluster_mongos02_config:

  mongodb_cluster_configs01_db:
  mongodb_cluster_configs01_config:

  mongodb_cluster_configs02_db:
  mongodb_cluster_configs02_config:

  mongodb_cluster_configs03_db:
  mongodb_cluster_configs03_config:

  mongodb_cluster_shard01_a_db:
  mongodb_cluster_shard01_a_config:

  mongodb_cluster_shard01_b_db:
  mongodb_cluster_shard01_b_config:

  mongodb_cluster_shard01_c_db:
  mongodb_cluster_shard01_c_config:

  mongodb_cluster_shard02_a_db:
  mongodb_cluster_shard02_a_config:

  mongodb_cluster_shard02_b_db:
  mongodb_cluster_shard02_b_config:

  mongodb_cluster_shard02_c_db:
  mongodb_cluster_shard02_c_config:

  mongodb_cluster_shard03_a_db:
  mongodb_cluster_shard03_a_config:

  mongodb_cluster_shard03_b_db:
  mongodb_cluster_shard03_b_config:

  mongodb_cluster_shard03_c_db:
  mongodb_cluster_shard03_c_config:
